# Generated by Django 3.2.16 on 2022-11-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_class', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogaclass',
            name='introduction',
            field=models.CharField(default='intro', max_length=300),
        ),
    ]
