# Generated by Django 3.2.16 on 2022-11-30 14:25

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_class', '0002_yogaclass_introduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('introduction', models.CharField(default='intro', max_length=300)),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='yogaclass',
            name='description',
        ),
        migrations.RemoveField(
            model_name='yogaclass',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='yogaclass',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='yogaclass',
            name='slug',
        ),
        migrations.AddField(
            model_name='yogaclass',
            name='days',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=15),
        ),
        migrations.AddField(
            model_name='yogaclass',
            name='times',
            field=models.CharField(choices=[('9:00 - 10:00', '9:00 - 10:00'), ('10:00 - 11:00', '10:00 - 11:00'), ('11:00 - 12:00', '11:00 - 12:00'), ('14:00 - 15:00', '14:00 - 15:00'), ('15:00 - 16:00', '15:00 - 16:00'), ('16:00 - 17:00', '16:00 - 17:00'), ('17:00 - 18:00', '17:00 - 18:00'), ('20:00 - 21:00', '20:00 - 21:00')], default='9:00 - 10:00', max_length=15),
        ),
        migrations.AlterField(
            model_name='yogaclass',
            name='yoga_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_class', to='book_class.yogatype'),
        ),
    ]
