# Generated by Django 3.2.16 on 2022-12-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yogaclass',
            old_name='days',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='yogaclass',
            old_name='times',
            new_name='time',
        ),
    ]
