# Generated by Django 3.2.16 on 2022-12-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_yogaclass_day_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yogaclass',
            options={'ordering': ['day']},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
