# Generated by Django 3.2.16 on 2022-12-18 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_note', to='bookings.reservation'),
        ),
    ]
